# Generated by Django 6.1 on 2026-09-09 07:29

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_productimage"),
        ("orders", "0001_initial"),
        ("tenancy", "0006_one_tenant_per_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending payment"),
                            ("paid", "Paid"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                (
                    "fulfillment_status",
                    models.CharField(
                        choices=[
                            ("unfulfilled", "Unfulfilled"),
                            ("fulfilled", "Fulfilled"),
                        ],
                        default="unfulfilled",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("shipping_name", models.CharField(max_length=160)),
                ("shipping_address_line_1", models.CharField(max_length=255)),
                (
                    "shipping_address_line_2",
                    models.CharField(blank=True, max_length=255),
                ),
                ("shipping_city", models.CharField(max_length=120)),
                ("shipping_region", models.CharField(blank=True, max_length=120)),
                ("shipping_postal_code", models.CharField(max_length=32)),
                ("shipping_country_code", models.CharField(max_length=2)),
                ("subtotal_cents", models.PositiveIntegerField()),
                ("shipping_cents", models.PositiveIntegerField()),
                ("total_cents", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"account_type": "customer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=160)),
                ("unit_price_cents", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                ("line_total_cents", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["tenant", "-created_at"], name="orders_orde_tenant__b7367d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_cents",
                        django.db.models.expressions.CombinedExpression(
                            models.F("subtotal_cents"), "+", models.F("shipping_cents")
                        ),
                    )
                ),
                name="order_total_matches_components",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="order_item_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "line_total_cents",
                        django.db.models.expressions.CombinedExpression(
                            models.F("unit_price_cents"), "*", models.F("quantity")
                        ),
                    )
                ),
                name="order_item_total_matches_price_quantity",
            ),
        ),
    ]
