# Generated by Django 6.1 on 2026-09-09 07:58

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "orders",
            "0002_order_orderitem_order_orders_orde_tenant__b7367d_idx_and_more",
        ),
        ("tenancy", "0006_one_tenant_per_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="idempotency_key",
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="session_key",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("tenant", "idempotency_key"),
                name="unique_order_idempotency_key_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("customer__isnull", False), ("session_key", "")),
                    models.Q(
                        ("customer__isnull", True),
                        models.Q(("session_key", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="order_has_customer_or_guest_session",
            ),
        ),
    ]
