# Generated by Django 6.1 on 2026-09-09 16:03

from django.db import migrations, models


def rename_fulfilled_status(apps, schema_editor):
    order = apps.get_model("orders", "Order")
    order.objects.filter(fulfillment_status="fulfilled").update(
        fulfillment_status="delivered"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_payment_method_alter_order_status"),
    ]

    operations = [
        migrations.RunPython(rename_fulfilled_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="order",
            name="fulfillment_status",
            field=models.CharField(
                choices=[
                    ("unfulfilled", "Unfulfilled"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default="unfulfilled",
                max_length=20,
            ),
        ),
    ]
