default_install_hook_types: [commit-msg]

repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.18.0
    hooks:
      - id: commitizen
        args: [--allow-abort, --message-length-limit, "72", --commit-msg-file]
        stages: [commit-msg]
