# Generated by Django 6.1 on 2026-09-04 15:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0005_tenant_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("price_cents", models.PositiveIntegerField()),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "slug"), name="unique_product_slug_per_tenant"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("price_cents__gte", 0)),
                        name="product_price_cents_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("stock_quantity__gte", 0)),
                        name="product_stock_quantity_nonnegative",
                    ),
                ],
            },
        ),
    ]
