# Generated by Django 6.1 on 2026-08-30 17:10

import accounts.managers
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("platform", "Platform"), ("customer", "Customer")],
                        max_length=20,
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="tenancy.tenant",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        models.F("tenant"),
                        condition=models.Q(("account_type", "customer")),
                        name="unique_customer_email_per_tenant",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("email"),
                        condition=models.Q(("account_type", "platform")),
                        name="unique_platform_email",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("account_type", "platform"), ("tenant__isnull", True)
                            ),
                            models.Q(
                                ("account_type", "customer"), ("tenant__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="user_tenant_matches_account_type",
                    ),
                ],
            },
            managers=[
                ("objects", accounts.managers.UserManager()),
            ],
        ),
    ]
