# Generated by Django 6.1 on 2026-09-14 11:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OutboundEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("deduplication_key", models.CharField(max_length=200, unique=True)),
                ("recipient", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("html_body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField()),
                ("last_error", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["sent_at", "next_attempt_at"],
                        name="accounts_ou_sent_at_87e98f_idx",
                    )
                ],
            },
        ),
    ]
