from django.urls import path

from catalog.views import (
    AdminProductDetailView,
    AdminProductImageDetailView,
    AdminProductImagePrimaryView,
    AdminProductImageUploadCompleteView,
    AdminProductImageUploadIntentView,
    AdminProductListCreateView,
    PublicProductDetailView,
    PublicProductListView,
)

urlpatterns = [
    path(
        "tenants/<slug:tenant_slug>/products/",
        PublicProductListView.as_view(),
        name="public-product-list",
    ),
    path(
        "tenants/<slug:tenant_slug>/products/<slug:product_slug>/",
        PublicProductDetailView.as_view(),
        name="public-product-detail",
    ),
    path(
        "tenants/<slug:tenant_slug>/admin/products/",
        AdminProductListCreateView.as_view(),
        name="admin-product-list",
    ),
    path(
        "tenants/<slug:tenant_slug>/admin/products/<uuid:pk>/",
        AdminProductDetailView.as_view(),
        name="admin-product-detail",
    ),
    path(
        "tenants/<slug:tenant_slug>/admin/products/"
        "<uuid:product_id>/images/upload-intent/",
        AdminProductImageUploadIntentView.as_view(),
        name="admin-product-image-upload-intent",
    ),
    path(
        "tenants/<slug:tenant_slug>/admin/products/<uuid:product_id>/images/"
        "<uuid:image_id>/complete/",
        AdminProductImageUploadCompleteView.as_view(),
        name="admin-product-image-upload-complete",
    ),
    path(
        "tenants/<slug:tenant_slug>/admin/products/<uuid:product_id>/images/"
        "<uuid:image_id>/",
        AdminProductImageDetailView.as_view(),
        name="admin-product-image-detail",
    ),
    path(
        "tenants/<slug:tenant_slug>/admin/products/<uuid:product_id>/images/"
        "<uuid:image_id>/primary/",
        AdminProductImagePrimaryView.as_view(),
        name="admin-product-image-primary",
    ),
]
