# Generated by Django 6.1 on 2026-08-30 18:00

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0002_tenantowner"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantHostname",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hostname", models.CharField(max_length=253)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("subdomain", "Platform subdomain"),
                            ("custom", "Custom domain"),
                        ],
                        default="subdomain",
                        max_length=20,
                    ),
                ),
                ("is_canonical", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostnames",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("hostname"),
                        name="unique_tenant_hostname_case_insensitive",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_canonical", True)),
                        fields=("tenant",),
                        name="one_canonical_hostname_per_tenant",
                    ),
                ],
            },
        ),
    ]
