# Generated by Django 6.1 on 2026-09-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0003_tenanthostname"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
