# Generated by Django 6.1 on 2026-09-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0004_tenant_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[
                    ("provisioning", "Provisioning"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("closed", "Closed"),
                ],
                default="provisioning",
                max_length=20,
            ),
        ),
    ]
