# Generated by Django 6.1 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0005_tenant_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tenantowner",
            constraint=models.UniqueConstraint(
                fields=("user",),
                name="one_tenant_per_owner",
            ),
        ),
    ]
