# Generated by Django 6.1 on 2026-09-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenancy", "0006_one_tenant_per_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="billing_required",
            field=models.BooleanField(default=False),
        ),
    ]
