# Generated by Django 6.1 on 2026-09-12 17:28

from django.db import migrations, models


def mark_existing_trials_used(apps, schema_editor):
    subscription = apps.get_model("billing", "TenantSubscription")
    subscription.objects.filter(
        models.Q(status="trialing") | models.Q(trial_ends_at__isnull=False)
    ).update(trial_used=True)


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_tenantsubscription_stripe_checkout_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsubscription",
            name="trial_used",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_trials_used, migrations.RunPython.noop),
    ]
