# Generated by Django 6.1 on 2026-09-13 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_tenantsubscription_trial_used"),
        ("tenancy", "0007_tenant_billing_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_invoice_id", models.CharField(max_length=255, unique=True)),
                ("stripe_customer_id", models.CharField(max_length=255)),
                (
                    "stripe_subscription_id",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("failed", "Failed")], max_length=20
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("amount_due_cents", models.PositiveBigIntegerField(default=0)),
                ("amount_paid_cents", models.PositiveBigIntegerField(default=0)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscription_payments",
                        to="tenancy.tenant",
                    ),
                ),
            ],
        ),
    ]
